variable "public-subnet1" {}
variable "public-subnet2" {}
variable "web-alb-sg-name" {}
variable "app-alb-sg-name" {}
variable "web-alb-name" {}
variable "app-alb-name" {}
variable "web-tg-name" {}
variable "app-tg-name" {}
variable "vpc-name" {}
variable "domain-name" {}